export enum StatusCodes {
  STATUS_CODE_OK = 200,
  STATUS_CODE_CREATED = 201,
  STATUS_CODE_ACCEPTED = 202,
  STATUS_CODE_NON_AUTHORITATIVE_INFORMATION = 203,
  STATUS_CODE_NO_CONTENT = 204,
  STATUS_CODE_RESET_CONTENT = 205,
  STATUS_CODE_PARTIAL_CONTENT = 206,

  //- Redirection
  STATUS_CODE_MULTIPLE_CHOICES = 300,
  STATUS_CODE_MOVED_PERMANENTLY = 301,
  STATUS_CODE_FOUND = 302,
  STATUS_CODE_SEE_OTHER = 303,
  STATUS_CODE_NOT_MODIFIED = 304,
  STATUS_CODE_TEMPORARY_REDIRECT = 307,
  STATUS_CODE_PERMANENT_REDIRECT = 308,

  //- Client Errors
  STATUS_CODE_BAD_REQUEST = 400,
  STATUS_CODE_UNAUTHORIZED = 401,
  STATUS_CODE_PAYMENT_REQUIRED = 402,
  STATUS_CODE_FORBIDDEN = 403,
  STATUS_CODE_NOT_FOUND = 404,
  STATUS_CODE_METHOD_NOT_ALLOWED = 405,
  STATUS_CODE_NOT_ACCEPTABLE = 406,
  STATUS_CODE_REQUEST_TIMEOUT = 408,
  STATUS_CODE_CONFLICT = 409,
  STATUS_CODE_GONE = 410,
  STATUS_CODE_UNSUPPORTED_MEDIA_TYPE = 415,
  STATUS_CODE_UNPROCESSABLE_ENTITY = 422,
  STATUS_CODE_TOO_MANY_REQUESTS = 429,

  //- Server Errors
  STATUS_CODE_INTERNAL_SERVER_ERROR = 500,
  STATUS_CODE_NOT_IMPLEMENTED = 501,
  STATUS_CODE_BAD_GATEWAY = 502,
  STATUS_CODE_SERVICE_UNAVAILABLE = 503,
  STATUS_CODE_GATEWAY_TIMEOUT = 504,
  STATUS_CODE_HTTP_VERSION_NOT_SUPPORTED = 505
}
